### ISSUE TITLE
Proposed division of Task View

### ISSUE THREAD

**Issue by leeper** [ropensci/opendata#114]
I would propose we do the following in order to get this onto CRAN:
1. [x] Approach Max Kuhn who maintains [the Reproducible Research Task View](https://cran.r-project.org/web/views/ReproducibleResearch.html) and see if we could move the key packages from the [Data Sharing and Archiving](https://github.com/ropensci/opendata#data-sharing-and-archiving) section to that Task View. (Many of these are mentioned on Web Technologies, as well.)
2. [x] Focus this task view, [as Achim suggested](https://github.com/ropensci/opendata/issues/4#issuecomment-145132671), only on web-based open data resources.
   - [x] Update the lede text to describe narrower focus
   - [x] Try to organize existing, longer sections (e.g., [Earth Science](https://github.com/ropensci/opendata/#earth-science) and [Ecology](https://github.com/ropensci/opendata/#ecological-and-evolutionary-biology)) so that resources are subcategorized.
3. [x] Document licensing of the various data resources as discussed previously in #4.
4. [x] Creating and publicizing a package that simply subsets `available.packages()` to be able to describe the universe of data-only packages available on CRAN. (It would not import them, just have tools for drawing peoples' attention to data-specific packages.)

Thoughts, @ashander @sckott?

**Comment by leeper** [comment]
I've created a mockup of the package to list available data packages here: https://github.com/leeper/crandatapkgs

It implements one function, `available_data()` that returns a data.frame of known data packages.

**Comment by sckott** [comment]
sounds good to me. I don't particularly like Achim's suggestion - this is _open data_, not _non-static open data_, but i don't think it's worth fighting him over it.

**Comment by ashander** [comment]
@leeper sorry I missed this last week. Yes this looks like a good idea

**Comment by ashander** [comment]
1. @leeper do you know Max Kuhn / are you planning to do 1?
2. I will implement Achim's suggestions (updating lede and splitting text)
3. I edited to check this, because I did it earlier (I think -- I added $ or other markers for paid services).

**Comment by leeper** [comment]
I don't know Max, but can reach out to him.

**Comment by ashander** [comment]
In #121  the lead is narrowed, data sharing and archiving removed.

In  #120 the Earth Science section is split up. Next will do Ecology

**Comment by ashander** [comment]
With #121 and #120 I think we're done with @leeper 's checklist. I just merged #120 bc it's good to do independently of the lead and data sharing stuff.

But,
- [ ] we haven't heard back from Max

And, I could take a stab at this to meet Achim's request:
- [ ] removing the github-only packages, or (preferably?) altering Make to remove the github-only packages from the cran submission

**Comment by sckott** [comment]
What's the status with getting this to CRAN? What are the things Achim wants changed?

**Comment by ashander** [comment]
Per https://github.com/ropensci/opendata/issues/114#issuecomment-195804572 he wanted the github-only packages removed. 

Not sure if @leeper ever heard back from Max Kuhn about 

> 1. [x] Approach Max Kuhn who maintains [the Reproducible Research Task View](https://cran.r-project.org/web/views/ReproducibleResearch.html) and see if we could move the key packages from the [Data Sharing and Archiving](https://github.com/ropensci/opendata#data-sharing-and-archiving) section to that Task View. (Many of these are mentioned on Web Technologies, as well.)

**Comment by sckott** [comment]
do you think it'd be easy enough to adjust Make to remove github only pkgs?

**Comment by ashander** [comment]
heh. seems like yes #278

**Comment by sckott** [comment]
cool, you going to finish that off? or too busy?

**Comment by ashander** [comment]
I'll read through and change anything that sticks out. 

But it'd be good to get a second set of eyes on it before I send to Achim, so I'll ask for a review on that PR after I take a look

**Comment by sckott** [comment]
okay

**Comment by ashander** [comment]
OK @leeper or @sckott  take a look at #278 

also before submitting there's this issue of where to put the Data Sharing and Archiving section (Max Kuhn's ctv, if he's interested?)

**Comment by sckott** [comment]
Hmm, I guess if no response from Max then that's not an option, right?  Could spin off a new task view :gulp:
