### ISSUE TITLE
Add rsdmx

### ISSUE THREAD

**Issue by eblondel** [ropensci/opendata#158]
Hello, would it be possible to add rsdmx package?
rsdmx offers an interface to web-data provided through SDMX web-services. I've seen that you already listed RJSDMX, rsdmx is alternative to it. Since the goal is the same (while list of data providers slightly differs between the 2 packages), i prefer asking in a ticket first on how you would mention rsdmx (maybe avoid redundancy in package description). Thanks in advance!

**Comment by leeper** [comment]
Thanks. I'll add it.

**Comment by ashander** [comment]
Sorry this took a bit :D

**Comment by eblondel** [comment]
thanks for that!
