### ISSUE TITLE
energyr

### ISSUE THREAD

**Issue by sckott** [ropensci/opendata#178]
good fit?

github https://github.com/paulgovan/energyr
cran https://cran.rstudio.com/web/packages/energyr/

**Comment by ashander** [comment]
Yes. Although it's broad and I'm unsure which of our existing categories fits:

>Data published by the United States Federal Energy Regulatory Commission including electric company financial data, natural gas company financial data, hydropower plant data, liquified natural gas plant data, oil company financial data natural gas company financial data, and natural gas storage field data.

**Comment by ashander** [comment]
nm found the right place
