### ISSUE TITLE
CONTIRBUTING.md points of confusion (for me at least!)

### ISSUE THREAD

**Issue by jhollist** [ropensci/opendata#210]
Two thing tripped me up on a recent PR.

1.) OpenData.html is currently ignored, but mentioned in CONTRIBUTING.md.  Unclear if this should be part of the PR.  I assumed not since ignored.
2.) the checkctv target does not exist in the Makefile.

**Comment by leeper** [comment]
Thanks. Sorry this wasn't clearer. `checkctv` should have been `check` and, no, you don't have to do anything with OpenData.html. Should be fixed now.

**Comment by jhollist** [comment]
Thanks!  I figured it was the check target but my make skills are lacking so I wasn't entirely sure...
