### ISSUE TITLE
Still taking contributions? Ever going to CRAN?

### ISSUE THREAD

**Issue by briatte** [ropensci/opendata#279]
Hi,

I'm working on updating [this Web page](https://f.briatte.org/teaching/quanti/data/), and thinking about submitting updates and suggestions to your CRAN Task View, as well as to a few others, based on my review.

Are you still updating this page, and will it ever go to CRAN?

All the best,

François

**Comment by Rekyt** [comment]
Hi @briatte,
As you never got any answer and the fact that the last commit on this Task View has been in 2017 (!), I've realized that another Task View from rOpenSci is online and up-to-date: it is the Web Technologies Task View https://github.com/ropensci/webservices
A significant part of the Task View references package that extract data.

**Comment by briatte** [comment]
Thanks!
