### ISSUE TITLE
Many CRAN URLs are broken inc. Quandl

### ISSUE THREAD

**Issue by dmpe** [ropensci/opendata#63]
Quandl {!!!!} A package that interacts directly with the Quandl API to offer data in a number of formats usable in R, as well as the ability to upload and search.

It should be either https://cran.r-project.org/web/packages/Quandl/ or https://github.com/quandl/quandl-r

Thanks

**Comment by ashander** [comment]
Thanks. There's some issue with our system for building the README from opendata.md

**Comment by ashander** [comment]
Thanks! Fixed via #68
