### ISSUE TITLE
SocialMediaLab

### ISSUE THREAD

**Issue by leeper** [ropensci/opendata#86]
Seems to be a wrapper for a bunch of other packages: https://cran.r-project.org/web/packages/SocialMediaLab/index.html

**Comment by timothyjgraham** [comment]
Hi there! I am one of the authors of this package. It draws on other packages to collect social media data, but significantly extends the functionality by enabling users to construct different types of networks for analysis. It also provides support for YouTube, which does not appear to have a package yet.

**Comment by leeper** [comment]
@timothyjgraham Thanks! There is a YouTube pkg actually: https://github.com/soodoku/tuber

**Comment by leeper** [comment]
@timothyjgraham We will definitely be adding your package (with your updated description) to the task view, though.

**Comment by timothyjgraham** [comment]
Hi, thanks for letting me know about the YouTube package. When we started working on SocialMediaLab earlier this year there didn't appear to be anything available, but good to know this is available now!

Thanks for adding the package to the task view -- much appreciated. We have updated it to include more functionality for Instagram (creating ego networks of follower/follow relations). It will be updated on CRAN soon too. If you have any questions please feel free to touch base.
